wip

diff --git a/.github/actions/pr-check/action.yml b/.github/actions/pr-check/action.yml
--- a/.github/actions/pr-check/action.yml
+++ b/.github/actions/pr-check/action.yml
@@ -18,6 +18,20 @@ inputs:
     description: |
       The revision (commit SHA) of the base branch in the context of a pull request.
     required: true
+  configuration-file:
+    description: Path to the FOSSA configuration file
+    required: false
+    default: .fossa.yml
+  path:
+    description: Path to the directory for scanning
+    default: .
+    required: false
+  project:
+    description: |
+      The name of the scanned project.
+      Only for display purposes, not required.
+    default: main
+    required: false
   revision:
     description: |
       The revision (commit sha) of the HEAD branch in the context of a pull request.
@@ -29,13 +43,14 @@ runs:
   - name: Check for new issues against the base ref=${{ inputs.base-ref }}
     id: check
     env:
-      BASE_REF: ${{ inputs.base-ref }}
       BASE_REVISION: ${{ inputs.base-revision }}
+      CONFIGURATION_FILE: ${{ inputs.configuration-file }}
+      DIRECTORY_PATH: ${{ inputs.path }}
       FOSSA_API_KEY: ${{ inputs.api-key }}
       REVISION: ${{ inputs.revision }}
     run: |
       # Run fossa test
-      results=$(fossa test . --diff "${BASE_REVISION}" --revision "${REVISION}" --format json || true)
+      results=$(fossa test "${DIRECTORY_PATH}" --config "${CONFIGURATION_FILE}" --diff "${BASE_REVISION}" --revision "${REVISION}" --format json || true)
 
       license_issues=$(echo "$results" | jq -c '.issues | map(select(.type == "policy_flag"))')
       license_issues_count=$(echo "$license_issues" | jq '. | length')
@@ -43,7 +58,7 @@ runs:
       security_issues_count=$(echo "$security_issues" | jq '. | length')
 
       echo "License issues: ${license_issues_count}"
-      echo "Security issues: ${license_issues_count} (non-license issues are currently ignored)"
+      echo "Security issues: ${security_issues_count} (non-license issues are currently ignored)"
 
       echo "license-issues=${license_issues}" >> $GITHUB_OUTPUT
       echo "license-issues-count=${license_issues_count}" >> $GITHUB_OUTPUT
@@ -54,15 +69,13 @@ runs:
       FOSSA_API_KEY: ${{ inputs.api-key }}
       LICENSE_ISSUES: ${{ steps.check.outputs.license-issues }}
       LICENSE_ISSUES_COUNT: ${{ steps.check.outputs.license-issues-count }}
-      JOB_NAME: ${{ github.job }}
+      PROJECT: ${{ inputs.project }}
     run: |
       echo "This PR introduces new license issues that must be addressed prior to merging."
       echo "HOW-TO: https://confluence.camunda.com/spaces/HAN/pages/277024795/FOSSA#FOSSA-Handlelicenseissues"
       echo "License Issues:"
       echo "${LICENSE_ISSUES}" | jq -r '.[] | "- Package: \(.revisionId)\n  License: \(.license)\n  Issue URL: \(.issueDashURL)\n"'
       echo "Adding an annotation to the GitHub job for visibility and exiting with error..."
-      echo "::error title=License Check::${LICENSE_ISSUES_COUNT} issue found. Please check the logs and resolve before merging."
-      echo "::error::New license issues detected. Please check the logs and resolve before merging."
-      echo "::error title=${{ github.job }}/License Check::${LICENSE_ISSUES_COUNT} issue found. Please check the logs and resolve before merging."
+      echo "::error title=License Check (project=${PROJECT})::${LICENSE_ISSUES_COUNT} issue found. Please check the logs and resolve before merging."
       exit 1
     shell: bash
